In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

In [2]:
def train_test_split(df_x, df_y, test_size, random_state):
    X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=test_size,random_state=random_state)
#    train_set = pd.concat([X_train, y_train], axis=1)
#    test_set = pd.concat([X_test, y_test], axis=1)
    return X_train, y_train

In [4]:
df_x = pd.read_csv("C:\\Users\\pgarciag\\Documents\\GitHub\\DataPreprocessing25022023\\final_data.csv")

In [7]:
df_x = df_x.drop(['Unnamed: 0'], axis=1)

KeyError: "['Unnamed: 0'] not found in axis"

In [8]:
df_x

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1.472734,0.668790,0.460382,0.624077,0.511159,-0.132088,0.375828,0.452910,1.557442,1.471797,1.0,0.0,0.0
1,-0.656012,0.133791,-0.119901,-0.187211,-0.294363,-0.550098,-0.854260,-1.015913,-0.831912,-0.671671,0.0,0.0,1.0
2,0.186737,1.043290,0.856674,0.909125,0.788692,0.272017,-0.416499,0.371308,0.562039,0.176906,0.0,1.0,0.0
3,-0.854035,-1.410065,-1.414924,-1.546668,-1.478954,-1.334891,-0.495732,-0.852711,-1.485903,-0.871064,1.0,0.0,0.0
4,-0.344011,-1.211351,-1.273392,-1.188531,-1.208190,-1.120032,-0.289161,-0.444704,-0.161855,-0.357512,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,-0.421148,-0.271280,-0.325123,0.163616,0.274241,-0.028756,0.375828,0.779315,-0.302398,-0.435183,0.0,0.0,1.0
4666,2.636695,-0.370637,0.524072,-0.289536,0.132090,1.285867,0.015036,0.289707,2.109155,2.643806,1.0,0.0,0.0
4667,-0.422299,-0.080209,0.241007,-0.194520,0.125321,-0.160190,-0.036842,-0.444704,-0.304596,-0.436342,0.0,0.0,1.0
4668,-0.536277,-0.966780,-1.103553,-0.961955,-0.937427,-0.827454,0.128226,0.779315,-0.539370,-0.551108,0.0,1.0,0.0
4669,-0.170165,0.707005,1.281271,1.281879,1.824363,1.511850,0.615812,0.779315,0.114507,-0.182464,1.0,0.0,0.0

In [9]:
df_y = pd.read_csv("C:\\Users\\pgarciag\\Documents\\GitHub\\DataPreprocessing25022023\\final_Y.csv")

In [11]:
df_y = df_y.drop(['Unnamed: 0'], axis=1)

In [ ]:
train_test_split(df_x, df_y, 0.2, 100)